# Generated by Django 5.1.6 on 2025-02-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score5',
            field=models.IntegerField(default=0),
        ),
    ]
