# Generated by Django 5.1.6 on 2025-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerapp', '0003_user_quizzes_attempted_alter_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score5',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
