# Generated by Django 5.1.6 on 2025-02-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerapp', '0004_remove_user_score5_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_completed',
            field=models.IntegerField(default=0),
        ),
    ]
