# Generated by Django 5.1.6 on 2025-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerapp', '0005_user_level_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_completed',
            field=models.IntegerField(default=1),
        ),
    ]
